# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Resy < Formula
  desc "A CLI to easily schedule restaurant reservations in advance."
  homepage "https://github.com/lgrees/resy-cli"
  version "0.5.0"

  on_macos do
    url "https://github.com/lgrees/resy-cli/releases/download/v0.5.0/resy_0.5.0_darwin_all.tar.gz"
    sha256 "675a97fb3b41b01593b70cd68e4856b44a68f56845b742396ad25de0f90d8e3d"

    def install
      bin.install "resy"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lgrees/resy-cli/releases/download/v0.5.0/resy_0.5.0_linux_arm64.tar.gz"
      sha256 "cf72898dcb314d5c046b4e0825b595b4b45ecdefc77555620d21c2094b6d531e"

      def install
        bin.install "resy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lgrees/resy-cli/releases/download/v0.5.0/resy_0.5.0_linux_amd64.tar.gz"
      sha256 "1e17c0a4ee7eb0d81db14fb23414f37a51ac68ead7cc11c3efd9bf3cd775ffc7"

      def install
        bin.install "resy"
      end
    end
  end
end
