# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Resy < Formula
  desc "A CLI to easily schedule restaurant reservations in advance."
  homepage "https://github.com/lgrees/resy-cli"
  version "0.2.0"

  on_macos do
    url "https://github.com/lgrees/resy-cli/releases/download/v0.2.0/resy_0.2.0_darwin_all.tar.gz"
    sha256 "aaaa419cb80797475db8ac13ee1070c2f7028221ac87282f0821c82bf8eb0537"

    def install
      bin.install "resy"
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/lgrees/resy-cli/releases/download/v0.2.0/resy_0.2.0_linux_arm64.tar.gz"
      sha256 "5c212b9031076366a0aaf04de8a23bc98a5cb34bdd9eedcacef0ff2f6948418a"

      def install
        bin.install "resy"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/lgrees/resy-cli/releases/download/v0.2.0/resy_0.2.0_linux_amd64.tar.gz"
      sha256 "d573ad3366678e5980250267e10b731db3c26e70c1f9c9be33465eefb14308be"

      def install
        bin.install "resy"
      end
    end
  end
end
